services:

  postgres:
    image: postgres:15
    # container_name: transit_postgres
    # environment:
    #   POSTGRES_USER: transit
    #   POSTGRES_PASSWORD: transit
    #   POSTGRES_DB: transit
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    # container_name: transit_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    # container_name: transit_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      echo 'Waiting for Kafka...'
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic gtfs.trip_updates --replication-factor 1 --partitions 1
      # kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic vehicle-positions --replication-factor 1 --partitions 1
      # kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic alerts --replication-factor 1 --partitions 1
      # kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic my-topic-2 --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
  # realtime-producer:
  #   build: ./services/ingestion
  #   command: python -m realtime.gtfs_rt_producer
  #   depends_on:
  #     - kafka

  # realtime-consumer:
  #   build: ./services/ingestion
  #   command: python -m realtime.gtfs_rt_consumer
  #   depends_on:
  #     - kafka
  #     - postgres

  realtime-gtfs-producer:
    build:
      context: ./services/ingestion
    command: python -u -m realtime.gtfs_realtime_producer
    depends_on:
      - kafka
    env_file:
      - .env
    restart: unless-stopped

  realtime-gtfs-consumer:
    build:
      context: ./services/ingestion
    command: python -u -m realtime.gtfs_realtime_consumer
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  # static-gtfs-ingestion:
  #   build:
  #     context: ./services/ingestion
  #   command: python -m gtfs.load_gtfs
  #   volumes:
  #     - ./data:/data
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  static-gtfs-ingestion:
    build:
      context: ./services/ingestion
    command: python -u -m gtfs.load_gtfs
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    env_file:
      - .env
    profiles:
      - batch

  # dagster-webserver:
  #   image: dagster/dagster:1.5.10
  #   command: dagster-webserver -h 0.0.0.0 -p 3000
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./dagster_project:/opt/dagster/app

  # dagster-daemon:
  #   image: dagster/dagster:1.5.10
  #   command: dagster-daemon run
  #   volumes:
  #     - ./dagster_project:/opt/dagster/app
  #   depends_on:
  #     - dagster-webserver

  # api:
  #   image: python:3.11-slim
  #   # container_name: transit_api
  #   working_dir: /app
  #   volumes:
  #     - ./services/api:/app
  #   command: sleep infinity
  #   ports:
  #     - "8000:8000"

  # api:
  #   image: python:3.11-slim
  #   working_dir: /app
  #   volumes:
  #     - ./services/api:/app
  #     - ./services/scoring:/scoring
  #   command: >
  #     sh -c "pip install fastapi uvicorn && 
  #           uvicorn main:app --host 0.0.0.0 --port 8000"
  #   ports:
  #     - "8000:8000"

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - otp
      - kafka
    ports:
      - "8000:8000"

  otp:
    image: opentripplanner/opentripplanner:2.5.0
    ports:
      - "8088:8080"
    volumes:
      - ./data:/var/opentripplanner
    command: >
      --build --serve

  # ingestion:
  #   build: ./services/ingestion
  #   volumes:
  #     - ./data:/data
  #   depends_on:
  #     - postgres

  # ingestion:
  #   build:
  #     context: ./services/ingestion
  #   volumes:
  #     - ./services/ingestion:/app
  #     - ./data:/data
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env


  flink-jobmanager:
    build:
      context: ./services/flink
      dockerfile: Dockerfile.flink
    ports:
      - "8081:8081"
    volumes:
      - ./services/flink:/opt/flink/usrlib
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.memory.process.size: 1600m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
      interval: 5s
      timeout: 3s
      retries: 20

  flink-taskmanager:
    build:
      context: ./services/flink
      dockerfile: Dockerfile.flink
    volumes:
      - ./services/flink:/opt/flink/usrlib
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 15
        parallelism.default: 3

  # flink-submit:
  #   build:
  #     context: ./services/flink
  #     dockerfile: Dockerfile.flink
  #   depends_on:
  #     - flink-jobmanager
  #     - flink-taskmanager
  #   volumes:
  #     - ./services/flink:/opt/flink/usrlib
  #   command: >
  #     bash -c "
  #     echo 'Waiting for Flink cluster...' &&
  #     sleep 15 &&
  #     flink run -py /opt/flink/usrlib/job.py
  #     "
  #   restart: unless-stopped

  flink-submit:
    build:
      context: ./services/flink
      dockerfile: Dockerfile.flink
    depends_on:
      flink-jobmanager:
        condition: service_healthy
      flink-taskmanager:
        condition: service_started
    volumes:
      - ./services/flink:/opt/flink/usrlib
    command: >
      bash -c "
      echo 'Submitting Flink job...' &&
      flink run -py /opt/flink/usrlib/job.py
      "
    restart: unless-stopped
  


volumes:
  postgres_data:
  pgadmin_data:

# taskmanager:
#   deploy:
#     resources:
#       limits:
#         cpus: "2.0"
#         memory: 2G


