# FROM flink:2.2.0-scala_2.12-java17
# FROM flink:1.20.2-scala_2.12-java17
FROM flink:2.2.0-scala_2.12-java17

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

# ref: https://nightlies.apache.org/flink/flink-docs-release-2.2/docs/deployment/resource-providers/standalone/docker/#using-flink-python-on-docker

WORKDIR /opt/pyflink
COPY pyproject.toml .

# IMPORTANT: install python to shared location
USER root
ENV UV_PYTHON_INSTALL_DIR=/opt/python
RUN uv python install 3.11 && uv sync
# FIX permissions for flink user
RUN chown -R flink:flink /opt/pyflink
RUN chmod -R 755 /opt/pyflink

RUN chown -R flink:flink /opt/python
RUN chmod -R 755 /opt/python

USER flink

ENV PATH="/opt/pyflink/.venv/bin:$PATH"
ENV PYFLINK_PYTHON=/opt/pyflink/.venv/bin/python
ENV PYFLINK_DRIVER_PYTHON=/opt/pyflink/.venv/bin/python

# Kafka + JDBC connectors
WORKDIR /opt/flink/lib

# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/2.2.0/flink-json-2.2.0.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-2.2/flink-connector-jdbc-3.2.0-2.2.jar && \
#     wget https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.2.0-2.2/flink-connector-kafka-3.2.0-2.2.jar

# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-2.2/flink-connector-jdbc-3.2.0-2.2.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.2.0-2.2/flink-connector-kafka-3.2.0-2.2.jar && \
#     wget https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar


# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.0.0-1.17/flink-connector-jdbc-3.0.0-1.17.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.0.2-1.17/flink-connector-kafka-3.0.2-1.17.jar && \
#     wget https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar

# RUN wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.1-2.0/flink-sql-connector-kafka-4.0.1-2.0.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar; \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar

# this was almost good 
# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/4.0.1-2.0/flink-connector-kafka-4.0.1-2.0.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar; \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/kafka/kafka-clients/4.2.0/kafka-clients-4.2.0.jar;    


# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.0.2-1.17/flink-connector-kafka-3.0.2-1.17.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar; \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/kafka/kafka-clients/3.7.0/kafka-clients-3.7.0.jar;    



# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.3.0-1.20/flink-connector-kafka-3.3.0-1.20.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar && \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar


# # THIS WAS KIND OF WORKING VERSION !!  
# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.3.0-1.20/flink-connector-kafka-3.3.0-1.20.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar && \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/kafka/kafka-clients/3.7.0/kafka-clients-3.7.0.jar



# # SHOULD BE OK MINIMAL 
# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/4.0.1-2.0/flink-connector-kafka-4.0.1-2.0.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/4.0.0-2.0/flink-connector-jdbc-4.0.0-2.0.jar && \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/kafka/kafka-clients/4.2.0/kafka-clients-4.2.0.jar

# RECOMMENDED
RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/2.2.0/flink-json-2.2.0.jar && \
    wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/4.0.1-2.0/flink-connector-kafka-4.0.1-2.0.jar && \
    wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc-core/4.0.0-2.0/flink-connector-jdbc-core-4.0.0-2.0.jar && \
    wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc-postgres/4.0.0-2.0/flink-connector-jdbc-postgres-4.0.0-2.0.jar && \
    wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar && \
    wget https://repo.maven.apache.org/maven2/org/apache/kafka/kafka-clients/4.2.0/kafka-clients-4.2.0.jar

    # wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-kafka/3.0.2-1.17/flink-connector-kafka-3.0.2-1.17.jar && \

    # https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar

# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/2.2.0/flink-json-2.2.0.jar; \
#     wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.1-2.0/flink-sql-connector-kafka-4.0.1-2.0.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc-core/4.0.0-2.0/flink-connector-jdbc-core-4.0.0-2.0.jar; \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc-postgres/4.0.0-2.0/flink-connector-jdbc-postgres-4.0.0-2.0.jar; \
#     wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar


# RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/2.2.0/flink-json-2.2.0.jar && \
#     wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-2.2/flink-connector-jdbc-3.2.0-2.2.jar && \
#     wget https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.7.10/postgresql-42.7.10.jar
# COPY flink-config.yaml /opt/flink/conf/config.yaml

WORKDIR /opt/flink